audit_header: false
title: Phoenix's Best Real Estate Training
description: Curtis Johnson, a top Real Estate Agent in Phoenix, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Curtis Johnson
  title:
  license_number:
  about_markdown: |
    One of the most connected and sought after minds in real estate, Curtis runs a highly successful real estate team, having sold over 3,000 residential homes. The Wall Street Journal ranked Curtis Johnson Realty as one of the Top 50 out of 1.2 million REALTORS in America.

    After years of dissecting the real estate transaction and discovering the key elements that affect the sale - he flipped the typical real estate transaction on its head. He systematized the process, resulting in his exclusive 89 Step No Risk Home Sale, and 47 Step Home Discovery and Acquisition Method.

    Curtis has been featured nationally on the cover of REALTOR Magazine, prominently in CNN Money Magazine as well as interviewed locally on virtually every TV station and newspaper. Curtis and his selling system have been featured on the 60 Minutes equivalent in several countries internationally.
  market: Phoenix
  brand: The Curtis Johnson Team
  brokerage: EXP Realty
  address: 2450 South Gilbert Rd. Ste 211<br>Chandler, AZ 85286
  phone: 480-355-4000
  phone_type:
  phone2:
  phone2_type:
  email: Curtis@CurtisJohnsonRealty.com
  url: http://www.CurtisJohnson.com

CTAs:
  first_CTA_text: Request a Consultation
  first_CTA_URL: /contact/

sidebar_CTA:
  - CTA_image_path: 'https://lh5.googleusercontent.com/proxy/V9aLZKkQrMp5XTS9sOr7LymNyck_AVJ_gvu_tGfKBwwkf1pwq6YGvfaWCfpFqZ2gU3s=s0-d'
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: "Let's talk about how The Curtis Johnson Team can take your business to new heights."
    CTA_link_text: Request a Free Strategy Session
    CTA_url: '/contact/'


lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/curtisjohnsonrealtyaz
  linkedin_url: https://www.linkedin.com/pub/curtis-johnson/6/45/aa5
  gplus_url: https://plus.google.com/105629530708977286822/about
  youtube_url: https://www.youtube.com/channel/UCkcQm7SVBRvka2OrbLuMs0A
  twitter_url: https://twitter.com/curtisjohnsonaz
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/curtisjohnsonrealty1/
  trulia_url: http://www.trulia.com/profile/curtis-johnson--agent-gilbert-az-18204886/overview
  yelp_url: http://www.yelp.com/biz/curtis-johnson-realty-gilbert-2
  podcast_url: https://itunes.apple.com/us/podcast/phoenix-real-estate-podcast/id1183106291?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: -- MARKET -- Real Estate Careers Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#CBAB66'
  theme_color: '#323232'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#eeeeee'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
